from pathlib import Path
import shutil, subprocess
OUT=Path('/root/.openclaw/workspace/outputs/la-school-static-atitude-palco')
AS=OUT/'assets'; AS.mkdir(parents=True,exist_ok=True)
REPO=Path('/root/.openclaw/workspace/repos/la-hq-agents')
files={
 'photo.png': Path('/root/.openclaw/media/tool-image-generation/test-halftone-behind-singer-soft-gradient---b9e1d2c7-ce53-4fb3-884c-60c641230522.png'),
 'logo.svg': REPO/'shared/brand-assets/logos/school/logo-la-music-dark-completa.svg',
 'font-black.ttf': REPO/'shared/brand-assets/fonts/school/Prompt-Black.ttf',
 'font-bold.ttf': REPO/'shared/brand-assets/fonts/school/Prompt-Bold.ttf',
 'font-regular.ttf': REPO/'shared/brand-assets/fonts/school/Prompt-Regular.ttf',
}
for name,src in files.items(): shutil.copy2(src, AS/name)
html = r'''<!doctype html><html><head><meta charset="utf-8"><style>
@font-face{font-family:Prompt;src:url('assets/font-black.ttf') format('truetype');font-weight:900}
@font-face{font-family:Prompt;src:url('assets/font-bold.ttf') format('truetype');font-weight:700}
@font-face{font-family:Prompt;src:url('assets/font-regular.ttf') format('truetype');font-weight:400}
:root{--pink:#E91451;--deep:#740A28;--black:#0A0A0A;--white:#fff}
*{box-sizing:border-box}body{margin:0;background:#111;font-family:Prompt,Arial,sans-serif}.post{width:1080px;height:1350px;position:relative;overflow:hidden;background:#0A0A0A;color:#fff}.photo{position:absolute;inset:0;z-index:1}.photo img{width:100%;height:100%;object-fit:cover;object-position:center center;filter:contrast(1.06) saturate(1.08)}.shade{position:absolute;inset:0;z-index:2;background:linear-gradient(180deg,rgba(0,0,0,.58) 0%,rgba(0,0,0,.05) 30%,rgba(0,0,0,.20) 54%,rgba(0,0,0,.92) 100%)}.edge{position:absolute;inset:0;z-index:3;background:radial-gradient(ellipse at 20% 70%,rgba(233,20,81,.45),transparent 36%),radial-gradient(ellipse at 85% 18%,rgba(116,10,40,.46),transparent 34%);mix-blend-mode:screen;opacity:.62}.faceLight{position:absolute;inset:0;z-index:4;background:radial-gradient(ellipse at 53% 24%,rgba(255,210,220,.22),transparent 22%);mix-blend-mode:screen;pointer-events:none}.logo{position:absolute;top:42px;left:54px;right:auto;display:flex;justify-content:flex-start;z-index:20}.logo img{height:58px;max-width:280px;filter:drop-shadow(0 6px 14px rgba(0,0,0,.85))}.copy{position:absolute;left:66px;right:66px;bottom:168px;z-index:10}.kicker{display:inline-flex;align-items:center;gap:14px;font-size:24px;font-weight:900;letter-spacing:3px;text-transform:uppercase;color:var(--pink);margin-bottom:22px;text-shadow:0 3px 12px rgba(0,0,0,.9)}.kicker:before{content:'';width:54px;height:6px;background:var(--pink);display:block;transform:skewX(-25deg)}h1{margin:0;font-weight:900;text-transform:uppercase;font-size:106px;line-height:.84;letter-spacing:-5.5px;text-shadow:0 7px 20px rgba(0,0,0,.86)}.outline{color:transparent;-webkit-text-stroke:4.1px #fff;text-stroke:4.1px #fff;text-shadow:0 5px 16px rgba(0,0,0,.95)}.pink{color:var(--pink)}.sub{max-width:760px;margin-top:24px;font-size:31px;line-height:1.16;font-weight:700;color:#fff;text-shadow:0 5px 16px rgba(0,0,0,.85)}.footer{position:absolute;bottom:48px;left:0;right:0;display:flex;flex-direction:column;align-items:center;z-index:25}.pill{display:inline-flex;align-items:center;gap:13px;background:var(--pink);color:#fff;padding:14px 31px;border-radius:999px;font-weight:900;font-size:19px;text-transform:uppercase;letter-spacing:1.4px;box-shadow:6px 7px 0 rgba(0,0,0,.75)}.ig{width:23px;height:23px;border:2px solid #fff;border-radius:6px;position:relative}.ig:after{content:'';position:absolute;top:50%;left:50%;width:8px;height:8px;border:2px solid #fff;border-radius:50%;transform:translate(-50%,-50%)}.stripes{display:flex;gap:8px;margin-top:14px}.stripes i{display:block;width:36px;height:7px;background:#fff;transform:skewX(-25deg)}.chev{position:absolute;right:66px;bottom:170px;z-index:11;color:var(--pink);font-size:64px;font-weight:900;letter-spacing:-8px;text-shadow:0 5px 14px rgba(0,0,0,.7)}
</style></head><body><section class="post"><div class="photo"><img src="assets/photo.png"></div><div class="shade"></div><div class="edge"></div><div class="faceLight"></div><div class="logo"><img src="assets/logo.svg"></div><div class="copy"><div class="kicker">atitude de palco</div><h1>CANTE<br><span class="outline">COMO QUEM</span><br><span class="pink">TEM ALGO</span><br>A DIZER</h1><div class="sub">A voz começa no corpo. A presença começa na coragem.</div></div><div class="chev">» » »</div><div class="footer"><div class="pill"><span class="ig"></span>@lamusicschool</div><div class="stripes"><i></i><i></i><i></i><i></i></div></div></section></body></html>'''
(OUT/'post.html').write_text(html)
subprocess.run(['/usr/local/bin/chromium','--headless','--no-sandbox','--disable-gpu','--window-size=1080,1350',f'--screenshot={OUT/"la-school-post-atitude-palco.png"}',(OUT/'post.html').as_uri()],check=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
subprocess.run(['tar','-czf',str(OUT.with_suffix('.tar.gz')),'-C',str(OUT.parent),OUT.name],check=True)
print(OUT/'la-school-post-atitude-palco.png')
print(OUT.with_suffix('.tar.gz'))
