-- LAHQ Supabase cleanup plan — SAFE / REVERSIBLE
-- Generated by Alfredo on 2026-05-13
-- DO NOT run blindly in production. Review in Supabase SQL Editor first.
-- Phase 0 is read-only verification. Phase 1 blocks accidental writes.
-- This script intentionally does NOT DROP any table.

begin;

-- ============================================================
-- PHASE 0 — dependency/row-count verification (read-only SELECTs)
-- Run these first and inspect results before any change.
-- ============================================================

-- Row counts for candidate tables
select 'shared_memory' table_name, count(*) rows from public.shared_memory union all
select 'bio_links', count(*) from public.bio_links union all
select 'boosts', count(*) from public.boosts union all
select 'budget_decisions', count(*) from public.budget_decisions union all
select 'campaigns', count(*) from public.campaigns union all
select 'contacts', count(*) from public.contacts union all
select 'dispatches', count(*) from public.dispatches union all
select 'email_bounces', count(*) from public.email_bounces union all
select 'kpi_snapshots', count(*) from public.kpi_snapshots union all
select 'leads', count(*) from public.leads union all
select 'meetings', count(*) from public.meetings union all
select 'post_metrics', count(*) from public.post_metrics union all
select 'schedule_entries', count(*) from public.schedule_entries union all
select 'ig_blocked_users', count(*) from public.ig_blocked_users;

-- Foreign-key dependencies involving candidates.
-- If this returns rows, inspect before changing anything.
select
  tc.constraint_name,
  tc.table_schema,
  tc.table_name,
  kcu.column_name,
  ccu.table_schema as foreign_table_schema,
  ccu.table_name as foreign_table_name,
  ccu.column_name as foreign_column_name
from information_schema.table_constraints tc
join information_schema.key_column_usage kcu
  on tc.constraint_name = kcu.constraint_name
 and tc.table_schema = kcu.table_schema
join information_schema.constraint_column_usage ccu
  on ccu.constraint_name = tc.constraint_name
 and ccu.table_schema = tc.table_schema
where tc.constraint_type = 'FOREIGN KEY'
  and (
    tc.table_name in ('shared_memory','bio_links','boosts','budget_decisions','campaigns','contacts','dispatches','email_bounces','kpi_snapshots','leads','meetings','post_metrics','schedule_entries','ig_blocked_users','squads')
    or ccu.table_name in ('shared_memory','bio_links','boosts','budget_decisions','campaigns','contacts','dispatches','email_bounces','kpi_snapshots','leads','meetings','post_metrics','schedule_entries','ig_blocked_users','squads')
  )
order by tc.table_name, tc.constraint_name;

-- View dependencies involving candidates.
select
  vtu.view_schema,
  vtu.view_name,
  vtu.table_schema,
  vtu.table_name
from information_schema.view_table_usage vtu
where vtu.table_name in ('shared_memory','bio_links','boosts','budget_decisions','campaigns','contacts','dispatches','email_bounces','kpi_snapshots','leads','meetings','post_metrics','schedule_entries','ig_blocked_users','squads')
order by vtu.view_name, vtu.table_name;

-- ============================================================
-- PHASE 1 — canonical docs table + deprecation registry
-- Safe: creates metadata only.
-- ============================================================

create table if not exists public.schema_deprecation_registry (
  object_schema text not null default 'public',
  object_name text not null,
  object_type text not null default 'table',
  status text not null check (status in ('active','keep_future','deprecated','archive_candidate','drop_candidate')),
  reason text,
  replacement text,
  decision_by text default 'Alf + Alfredo',
  decided_at timestamptz not null default now(),
  review_after timestamptz,
  primary key (object_schema, object_name, object_type)
);

insert into public.schema_deprecation_registry (object_name, status, reason, replacement, review_after)
values
  ('shared_memory','deprecated','0 rows; no operational JS usage detected','semantic_memory', now() + interval '30 days'),
  ('bio_links','keep_future','0 rows; planned link-bio/landing-page module; keep but block until implemented',null, now() + interval '30 days'),
  ('boosts','keep_future','0 rows; paid/boost module not active yet; keep but block until implemented',null, now() + interval '30 days'),
  ('budget_decisions','keep_future','0 rows; paid media/budget intelligence future module',null, now() + interval '30 days'),
  ('campaigns','keep_future','0 rows; referenced by future ads/leads tables',null, now() + interval '30 days'),
  ('contacts','keep_future','0 rows; CRM/newsletter future module',null, now() + interval '30 days'),
  ('dispatches','keep_future','0 rows; newsletter/dispatch future module',null, now() + interval '30 days'),
  ('email_bounces','keep_future','0 rows; dependent on dispatches future module',null, now() + interval '30 days'),
  ('kpi_snapshots','keep_future','0 rows; analytics module planned in skills/docs',null, now() + interval '30 days'),
  ('leads','keep_future','0 rows, but Tina monitor can insert leads; keep',null, now() + interval '30 days'),
  ('meetings','deprecated','0 rows; no operational usage detected',null, now() + interval '30 days'),
  ('post_metrics','keep_future','0 rows; Instagram metrics future module',null, now() + interval '30 days'),
  ('schedule_entries','keep_future','0 rows; scheduling module planned in skills/docs',null, now() + interval '30 days'),
  ('ig_blocked_users','keep_future','0 rows, but Tina monitor checks it; keep',null, now() + interval '30 days'),
  ('squads','active','1 row and referenced by agents/tasks; do not remove','agents.squad_id/tasks.squad_id', null)
on conflict (object_schema, object_name, object_type) do update
set status = excluded.status,
    reason = excluded.reason,
    replacement = excluded.replacement,
    review_after = excluded.review_after,
    decided_at = now();

-- ============================================================
-- PHASE 2 — optional write-block for truly deprecated empty tables
-- This prevents accidental population without deleting structure.
-- Recommended initially ONLY for shared_memory and meetings.
-- Requires RLS to be enabled; service_role still bypasses RLS, so scripts using service_role must also be updated/not use these.
-- ============================================================

alter table public.shared_memory enable row level security;
alter table public.meetings enable row level security;

drop policy if exists deprecated_no_insert_shared_memory on public.shared_memory;
create policy deprecated_no_insert_shared_memory
on public.shared_memory
for insert
with check (false);

drop policy if exists deprecated_no_update_shared_memory on public.shared_memory;
create policy deprecated_no_update_shared_memory
on public.shared_memory
for update
using (false)
with check (false);

drop policy if exists deprecated_no_insert_meetings on public.meetings;
create policy deprecated_no_insert_meetings
on public.meetings
for insert
with check (false);

drop policy if exists deprecated_no_update_meetings on public.meetings;
create policy deprecated_no_update_meetings
on public.meetings
for update
using (false)
with check (false);

-- ============================================================
-- PHASE 3 — future/manual only: archive/drop after 30 days
-- Not included intentionally. If no rows and no dependencies after review:
--   alter table public.<table> rename to deprecated_<table>;
-- or
--   create schema if not exists archive;
--   alter table public.<table> set schema archive;
-- Drop only after backup/export.
-- ============================================================

rollback;
-- Change ROLLBACK to COMMIT only after reviewing Phase 0 outputs and approving Phase 1/2.
